name: Org Member Joined Handler

on:
  repository_dispatch:
    types: [org-member-joined]

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue for new org member
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const member = "${{ github.event.client_payload.member }}";
            const org = "${{ github.event.client_payload.org }}";

            const title = `🎉 New member joined ${org}`;
            const body = `**${member}** has accepted the invitation and joined **${org}**.`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });
